server:
  port: 19091

spring:
  application:
    name: provider-a
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yaml
        group: DEFAULT_GROUP

management:
  endpoints:
    web:
      exposure:
        include: health,info
